kamikaze3_writer_api:
    resource: "@Kamikaze3WriterApiBundle/Controller/"
    type:     annotation
    prefix:   /api

kamikaze3_writer_core:
    resource: "@Kamikaze3WriterCoreBundle/Controller/"
    type:     annotation
    prefix:   /core

kamikaze3_writer_frontend:
    resource: "@Kamikaze3WriterFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
